### ISSUE TITLE
[MVP] Priority 1 Tasks

### ISSUE THREAD

**Issue by W3stside** [gnosis/gp-swap-ui#32]
### Operator and Tips
- [X] Create Operator redux state #31 @Velenir 
- [x] Get (mock) TIP for token @W3stside #33 & #35 

### Price Estimation
- [x] Sell Order: Calculate receiving tokens using the tip @W3stside #33 & #35 
- [x] Buy Order: Calculate sold tokens using the tip @W3stside #33 & #35 
- [ ] Make sure hops are handle properly

### Pending Transactions
- [x] Model transactions
- [x] Transactions global state: Pending, settled
- [x] Pending transaction counter
- [x] Notification of transactions
- [x] Create OBA trades
- [x] Handle exception signing a trade
- [ ] Handle success signing the trade
- [ ] Handle execution of trades

**Comment by anxolin** [comment]
Done!
