### ISSUE TITLE
Idea: Error Message

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#339]
Might be cool to add some cow theme to the error messages (e.g. sad cow or cow tipping image, spilled milk...) 
<img width="405" alt="Bildschirmfoto 2021-03-25 um 10 50 40" src="https://user-images.githubusercontent.com/34510341/112456399-075ce180-8d5b-11eb-9136-dd9e8c02612f.png">

**Comment by anxolin** [comment]
Good catch. I agree with the suggestion, also we should handle this error better and display also a nicer message. 
I'll move this to our backlog and rename this issue so it's more broad (Better and nicer error handling) 
@michelbio is working in finding some nice illustrations for the website exactly for these situations. 

## Tasks
* [ ] Improve message for error posting orders. We need to identify the types of errors, and display comprehensive messages for all of them. 
* [ ] Use a image/images for the error messages. One funny and easy way is to do a tipped cow saying something: https://en.wikipedia.org/wiki/Cowsay#:~:text=cowsay%20is%20a%20program%20that,bubbles%20rather%20than%20speech%20bubbles.%20. 
* [ ] Review other errors in the app, like error with normal transactions
* [ ] BONUS: We probably want to move to a separate issue. If there's a run-time unhandled error we show a white page. This is the same behaviour as uniswap, and although it should never happen, it did in the past (if you enter negative slippage, and in some other situations). The task would be to have a last resource error handling, that shows a cow saying that there was an internal error (instead of internal error, she should say something more funny though :P )

## Notes for implementation
The API already provide a type field that shows the kind of error. So we can use this to handle these situations. 
* MissingOrderData,
* InvalidSignature,
* DuplicateOrder,
* InsufficientFunds

However, I didn't see one for the error of the date being in the past.  @fleupold Is it possible that the swagger docs is not in sync with the types?

![image](https://user-images.githubusercontent.com/2352112/112600697-d25f9600-8e11-11eb-9275-2716bc8dabd0.png)

**Comment by fleupold** [comment]
Yes, good catch. It's not synced (https://github.com/gnosis/gp-v2-services/pull/417 updates it)

**Comment by MareenG** [comment]
I got several  `failed to fetch` error messages today and and the error message displayed in #357. As a user it is hard to understand what is going on.

**Comment by MareenG** [comment]
I started a list to collect the error messages.
[Here](https://docs.google.com/spreadsheets/d/1JWQHjoY-wxIleIQeDue8smw7CBiDLsoziOlPhZ5hAGc/edit#gid=0) we can add info on what caused the error and if it needs rewording and/or improved presentation
